version: '3.7'

services:
  postgres:
    container_name: matcha-postgres
    environment:
      PGDATA: /var/lib/postgresql/data/
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    image: postgres
    ports:
      - 54320:5432
    restart: unless-stopped
    volumes:
      - matcha-postgres:/var/lib/postgresql/data

  redis:
    container_name: matcha-redis
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - matcha-redis:/data

  matcha-api:
    build: .
    command: ./matcha
    container_name: matcha-api
    environment:
      - CONFIG_PATH=${CONFIG_PATH}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FORMAT=${LOGGER_FORMAT}
      - PG_ADDRESS=matcha-postgres:5432
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - REDIS_ADDRESS=matcha-redis:6379
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - EMAIL_SERVER_ADDRESS=${EMAIL_SERVER_ADDRESS}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - 8080
    restart: unless-stopped

volumes:
  matcha-postgres:
    driver: local
  matcha-redis:
    driver: local

networks:
  default:
    external:
      name: matcha
