version: '3.2'

services:
  postgres:
    container_name: matcha-postgres
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/data/
    image: postgres
    ports:
      - '54320:5432'
    restart: unless-stopped
    volumes:
      - matcha-postgres:/var/lib/postgresql/data

volumes:
  matcha-postgres:
    driver: local

networks:
  default:
    external:
      name: matcha
